### ISSUE TITLE
Error with c03_refval_override

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/bufr2netcdf#7]
As usual,  I come with an issue on an [undecodable bufr file](https://github.com/ARPA-SIMC/bufr2netcdf/files/5117822/err_with_c03.zip). This time wreport decodes it regularly but bufr2netcdf fails with message:
```
define_c03_refval_override is not implemented in this interpreter
```
this stack trace may help:
```
C DATA 203014
Change reference values, 14 bit reference values follow

Breakpoint 3, wreport::bulletin::Interpreter::define_c03_refval_override (
    this=0x7fffffffc660, code=1822) at bulletin/interpreter.cc:515
515	    throw error_unimplemented("define_c03_refval_override is not implemented in this interpreter");
(gdb) where
#0  wreport::bulletin::Interpreter::define_c03_refval_override (
    this=0x7fffffffc660, code=1822) at bulletin/interpreter.cc:515
#1  0x00007ffff4d340c9 in wreport::bulletin::Interpreter::b_variable (
    this=0x7fffffffc660, code=1822) at bulletin/interpreter.cc:134
#2  0x00007ffff4d349fb in wreport::bulletin::Interpreter::run (
    this=0x7fffffffc660) at bulletin/interpreter.cc:38
#3  0x0000000000413fc6 in b2nc::Plan::build (this=0x46c6c8, bulletin=...)
    at plan.cc:516
#4  0x000000000040c2a5 in b2nc::Arrays::add (this=0x46c6c8, bulletin=...)
    at arrays.cc:367
#5  0x00000000004076b0 in b2nc::NCFiller::add (this=0x46c6c8, bulletin=..., 
    raw="BUFR\000\001V\003\000\000\022\000\000b\001\200\000\252\035\000\024\b\016\026\000\000\000\000\064\000\001\252~H:\300\000R\026\065\200\\\201\244\000_3765e40         \001V:ǔ:ǔ\000\000\000\000F\000\000\000\000\000\031\000\000\001\200\203\016\a\036\a\037\203\377\301\226\307P\005\001\006\001\a\001\000\000\353\000\316#8\200\001x\000\000\066\066\063", '\000' <repeats 13 times>, "\377\377\240\271\060\262", '\000' <repeats 16 times>, "\017\311\aX\005\310\032B\220\261\254)\220", '\377' <repeats 12 times>, "\370\006C\231[\226\335", '\377' <repeats 15 times>...) at convert.cc:219
```
[err_with_c03.zip](https://github.com/ARPA-SIMC/bufr2netcdf/files/5117822/err_with_c03.zip)

**Comment by spanezz** [comment]
Ho fatto push di un branch issue7 in cui ho definito quei metodi. Se ho visto bene, non dovrebbero fare niente, l'override dovrebbe essere gestito trasparentemente dal decoder BUFR, e bufr2netcdf può ignorare che esista.

Prima di far merge in master, ti chiederei però di confermarmi se il NetCDF risultante ha quello che ti aspetti

**Comment by dcesari** [comment]
Per quanto posso giudicare mi pare corretto, grazie.
